In [1]:
import os; os.chdir('..')

In [2]:
from Utils.get_categories import get_top_labels_bulk_v2, get_top_labels_bulk

/home/ubuntu/EmbeddingsUsingGTEmodels/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
l= [
        'best cat ear headphones', 
        'absxbvchbd', 
        'mercedes'
    ]

In [4]:
get_top_labels_bulk(
    l.copy()
)

[' Computers_and_Electronics best cat ear headphones',
 ' Computers_and_Electronics absxbvchbd',
 ' Autos_and_Vehicles mercedes']

In [5]:
l

['best cat ear headphones', 'absxbvchbd', 'mercedes']

In [6]:
l

['best cat ear headphones', 'absxbvchbd', 'mercedes']

In [7]:
get_top_labels_bulk_v2(
l
)

['best cat ear headphones Computers_and_Electronics',
 'absxbvchbd Computers_and_Electronics',
 'mercedes Autos_and_Vehicles']

In [8]:
import numpy as np

In [9]:
def logit2prob(logit):
    # odds =np.exp(logit)
    # prob = odds / (1 + odds)
    prob= 1/(1+ np.exp(-logit))
    return np.round(prob, 3)


In [18]:
# logits

tensor([[0.0420, 0.0050, 0.0060, 0.0020, 0.0060, 0.0020, 0.0170, 1.0000, 0.0310,
         0.0050, 0.0000, 0.0000, 0.0080, 0.1820, 0.0000, 0.0120, 0.0030, 0.0010,
         0.0040, 0.0870, 0.0110, 0.0010, 0.0060, 0.0010, 0.0060, 0.0560, 0.0080],
        [0.0280, 0.0000, 0.0000, 0.0000, 0.0110, 0.0000, 0.1210, 0.9880, 0.0010,
         0.0020, 0.0000, 0.0000, 0.0000, 0.0030, 0.0000, 0.0020, 0.0030, 0.0010,
         0.0050, 0.0030, 0.0050, 0.0000, 0.0080, 0.0010, 0.0130, 0.0030, 0.0050],
        [0.0160, 0.0090, 0.0010, 1.0000, 0.0050, 0.0130, 0.0030, 0.1170, 0.0030,
         0.0060, 0.0830, 0.0000, 0.0080, 0.0420, 0.0970, 0.0770, 0.0130, 0.0000,
         0.1490, 0.0060, 0.0080, 0.0030, 0.0020, 0.0030, 0.0030, 0.0000, 0.0130]])

In [11]:
# logits= logit2prob(logits)
# logits

tensor([[0.0420, 0.0050, 0.0060, 0.0020, 0.0060, 0.0020, 0.0170, 1.0000, 0.0310,
         0.0050, 0.0000, 0.0000, 0.0080, 0.1820, 0.0000, 0.0120, 0.0030, 0.0010,
         0.0040, 0.0870, 0.0110, 0.0010, 0.0060, 0.0010, 0.0060, 0.0560, 0.0080],
        [0.0280, 0.0000, 0.0000, 0.0000, 0.0110, 0.0000, 0.1210, 0.9880, 0.0010,
         0.0020, 0.0000, 0.0000, 0.0000, 0.0030, 0.0000, 0.0020, 0.0030, 0.0010,
         0.0050, 0.0030, 0.0050, 0.0000, 0.0080, 0.0010, 0.0130, 0.0030, 0.0050],
        [0.0160, 0.0090, 0.0010, 1.0000, 0.0050, 0.0130, 0.0030, 0.1170, 0.0030,
         0.0060, 0.0830, 0.0000, 0.0080, 0.0420, 0.0970, 0.0770, 0.0130, 0.0000,
         0.1490, 0.0060, 0.0080, 0.0030, 0.0020, 0.0030, 0.0030, 0.0000, 0.0130]])

In [19]:
# for i in logits:
#     print(i)
#     print(
#         i.argmax().item()
#     )
#     print()

tensor([0.0420, 0.0050, 0.0060, 0.0020, 0.0060, 0.0020, 0.0170, 1.0000, 0.0310,
        0.0050, 0.0000, 0.0000, 0.0080, 0.1820, 0.0000, 0.0120, 0.0030, 0.0010,
        0.0040, 0.0870, 0.0110, 0.0010, 0.0060, 0.0010, 0.0060, 0.0560, 0.0080])
7

tensor([0.0280, 0.0000, 0.0000, 0.0000, 0.0110, 0.0000, 0.1210, 0.9880, 0.0010,
        0.0020, 0.0000, 0.0000, 0.0000, 0.0030, 0.0000, 0.0020, 0.0030, 0.0010,
        0.0050, 0.0030, 0.0050, 0.0000, 0.0080, 0.0010, 0.0130, 0.0030, 0.0050])
7

tensor([0.0160, 0.0090, 0.0010, 1.0000, 0.0050, 0.0130, 0.0030, 0.1170, 0.0030,
        0.0060, 0.0830, 0.0000, 0.0080, 0.0420, 0.0970, 0.0770, 0.0130, 0.0000,
        0.1490, 0.0060, 0.0080, 0.0030, 0.0020, 0.0030, 0.0030, 0.0000, 0.0130])
3

